INSERT INTO make(name) VALUES ('Starfleet'),('Borg'),('Cardassian'),('Jem"Hadar'),('Kazon'),('Klingon'), ('Romulan'), ('Vulcan'),('Xindi');

INSERT INTO model(name,make_id) VALUES ('Akira',1),('Ambassador',1),('Andromeda',1),('Antares',1),('Apollo',1),('BradBury',1),('Centaur',1),('Challenger',1),('Cheyenne',1),('Chimera',1),('Columbia',1),('Constellation',1),('Constitution',1),('Daedalus',1),('Defiant',1),('Deneva',1),('Dreadnought',1),('Einstien',1),('Erewon',1),('Excelsior',1),('Freedom',1),('Galaxy',1),('Galen',1),('Hokule"a',1),('Intrepid',1),('Istanbul',1),('Korolev',1),('Luna',1),('Marklin',1),('Mediterranean',1),('Merced',1),('Merian',1),('Miranda',1),('Mulciber',1),('Nebula',1),('New Orleans',1),('Niagara',1),('Norway',1),('Nova',1),('NX',1),('Oberth',1),('Odyssey',1),('Olympic',1),('Prometheus',1),('Reniassance',1),('Rigel',1),('Saber',1),('Sequoia',1),('Sovereign',1),('Sayuz',1),('Springfield',1),('Steamrunner',1),('Surak',1),('Sydney',1),('Theophrastus',1),('Vesta',1),('Wambundu',1),('Wells',1),('Yorkshire',1),('Zodiac',1);
INSERT INTO model(name,make_id) VALUES ('Cube',2),('Probe',2),('Queens Vessel',2),('Scout Ship',2),('Sphere',2),('Tactical Cube',2);
INSERT INTO model(name,make_id) VALUES ('Antares',3),('Cardassian ATR-4107',3),('Bojoran',3),('Battle Cruiser',3),('Bok"Nor',3),('Cruiser',3),('Destroyer',3),('Freighter',3),('Frigate',3),('Galor',3),('Groumall Type',3),('Hideki',3),('Keldon',3),('Patrol Ship',3),('Persuit Vessel',3),('Repair Ship',3),('Supply Ship',3),('Survey Vessel',3),('Transport',3),('Warship',3);
INSERT INTO model(name,make_id) VALUES ('Fighter',4),('Battle Cruiser',4),('Battleship',4);
INSERT INTO model(name,make_id) VALUES ('Fighter',5),('Frigate',5),('Predator',5),('Raider',5),('Shuttle',5);
INSERT INTO model(name,make_id) VALUES ('Bird-of-Prey',6),('Cargo Vessel',6),('Civian Transport',6),('Cruiser',6),('D4',6),('D5',6),('D7',6),('D12',6),('Freighter',6),('K"t"inga',6),('K"touch',6),('K"Vort',6),('Transport',6),('Negh"Var Warship',6),('Raptor',6),('Scout Ship',6),('Toron',6),('Vor"cha',6),('Warbird',6);
INSERT INTO model(name,make_id) VALUES ('Battle Cruiser',7),('Bird-of-Prey',7),('Cruiser',7),('D"deridex',7),('D7',7),('Drone Ship',7),('Interceptor',7),('Mining Vessel',7),('Patrol Ship',7),('Science Vessel',7),('Scorpian',7),('Scout Ship',7),('Shuttle',7),('Supply Ship',7),('Troop Ship',7),('Valdore',7),('Warbird',7);
INSERT INTO model(name,make_id) VALUES ('Appollo',8),('Civialian',8),('Cruiser',8),('D"Kyr',8),('D"Vahl',8),('Defense Vessel',8),('Fighter',8),('Maymora',8),('Science Vessel',8),('Shuttle',8),('Surak',8),('Survey Ship',8),('Suurok',8),('T"Plana-Hath',8),('Transport',8),('Starship',8);
INSERT INTO model(name,make_id) VALUES ('Aquatic Cruiser',9),('Aquatic Escape Pod',9),('Aquatic Scout Ship',9),('Arboreal Landing Craft',9),('Arboreal Starship',9),('Insectoid Patrol Ship',9),('Insectoid Shuttlecraft',9),('Insectoid Scout Ship',9),('Insectoid Starship',9),('Primate Starship',9),('Primate Shuttle',9),('Reptilian warship',9),('Shuttle',9),('Starship',9);
INSERT INTO customer(first_name,last_name,phone,email) VALUES ('James','Kirk','5555555555','kirk@enterprise.com'),('Spock','Of Vulcan','5555555556','spock@enterprise.com'),('Hikaru', 'Sulu','5474894895','Hikaru@Enterprise.com');
INSERT INTO vehicle(color, plate_number,plate_state,year,model_id) VALUES ('Red','ABC-123','Earth',2010,1);
INSERT INTO pass(exp_date,price,customer_id,vehicle_id) VALUES ('01/05/2010',19.99,1,1);